DefaultContentLanguage = "zh-cn"
author = "zz"
baseURL = "https://frostrainn.github.io/blog"
##baseURL = "https://frostrainn.github.io/"
copyright = "Copyright © 2008–2019"
disqusShortname = "Rysent"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "zh-cn"
theme = "hugo-theme-tokiwa"
title = "雾中花"
canonifyurls = true

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/杨任东竹石体-Light" 
description = """
那里的颜色正是常磐色。
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = true 
postDateFormat = "2006-1-2 15:04:05"

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "归档"
url = "/post/"
weight = 1
[[menu.main]]
name = "标签"
url = "/tags/"
weight = 2

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
bilibili = "https://live.bilibili.com/59601"
github = "http://github.com/frostrainn"
mail = "mailto:735134025@qq.com"
zhihu = "http://example.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]
